---

- name: Apache stuff
  hosts: ubuntu
  tasks:
    - name: Installing Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Copying index file
      ansible.builtin.template:
        src: index.html
        dest: /var/www/html/index.html



...
