---
- name: Loops stuff
  hosts: acloudguruservers
  tasks: 
    - name: Installing multiple packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - unzip
        - tree
        - telnet


