---

- name: permit root login
  hosts: ubuntu
  tasks:
    - name: replacing line
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
        backup: yes
      notify: Restart sshd

  
  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
