---

- name: This is for variables
  hosts: acloudguruservers
  vars:
    - package_name: httpd
  tasks:
    - name: install {{ package_name }}
      ansible.builtin.dnf:
        name: "{{ package_name }}"
        state: present


